name: 'Git Changelog Generator'
description: 'Generates a Git changelog using data from HEAD to the previous tag'
outputs:
  changelog:
    description: 'The generated changelog'
    value: ${{ steps.output.outputs.changelog }}
runs:
  using: 'composite'
  steps:
    - id: output
      run: ${{ github.action_path }}/action.sh
      shell: bash