name: 'Git Changelog Generator'
description: 'Generates a Git changelog using data from HEAD to the previous tag'
outputs:
  changelog:
    description: 'The generated changelog'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: action.sh
      shell: bash