name: 'Git Changelog Generator'
description: 'Generates a Git changelog using data from HEAD to the previous tag'
outputs:
  changelog:
    description: 'The generated changelog'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/action.sh
      shell: bash